

services:
  server:
    container_name: 
      my_app
    ports:
      - 5000:8000
    build: 
      context: .
    depends_on:
      - database
        

  database:
    image: 'postgres:15-alpine'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=111
      - POSTGRES_DB=finance
    volumes:
      - ./postgres_data:/var/lib/postgresql/data